# Generated by Django 4.2.4 on 2025-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_review_reviewed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_ratting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_ratting',
            field=models.IntegerField(default=0),
        ),
    ]
