# Generated by Django 4.2.4 on 2025-02-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review_avg_ratting_review_total_ratting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_ratting',
        ),
        migrations.RemoveField(
            model_name='review',
            name='total_ratting',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='avg_ratting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_ratting',
            field=models.IntegerField(default=0),
        ),
    ]
